### ISSUE TITLE
请问一个中间件需要多个依赖数据的情况下如何处理

### ISSUE THREAD

**Issue by sunkuo** [luin/express-di#12]
比如在一个路由里面，我需要依赖3个对象，这将导致中间件的参数超过3个（obj1,obj2,obj3,next） 但是这种情况下会被express当成处理错误的对象。这种情况下该如何处理？

**Comment by luin** [comment]
多少个都可以的，express-di 对外暴露给 express 就是 function (req, res, next) {} 这种形式

**Comment by sunkuo** [comment]
举个例子，我定义了
`
app.factory('order', function(req, next) {
    next(null, {id:'1'})
}) 
`
`
app.factory('user', function(req, next) {
    next(null,{name: 'name'})
})
`
`
app.factory('address', function(req, next) {
    next(null,{province: 'gd'})
})
`
最后我的一个路由会这样子依赖
`
router.put('/order/address', function(order, user, address, next){})
`

这种情况下，我的路由就会被当成处理错误的组件，通过访问Put /order/address 就走不通了

**Comment by luin** [comment]
不会被当成错误的，你可以看看代码调试一下，另外目前支持的版本是 Express 4.x

**Comment by sunkuo** [comment]
好的，谢谢。原因是我这边用了co-express这个组件导致的
