### ISSUE TITLE
Dependent dependencies

### ISSUE THREAD

**Issue by floatdrop** [luin/express-di#4]
Hi! Thank you for awesome tool for structuring middlewares. I like the way, how dependencies is resolved by argument name, but there is a some kind of missed feature, that would bump usage cases of express-di to the space.

Suppose I want to declare dependent factory `people2` on already defined `people1` and use it in `people2` code:

``` js
var express = require('express');
// Require express-di
require('express-di');
var app = express();

app.factory('people1', function(req, res, next) {
      next(null, { name: "Bob" });
});

app.factory('people2', function(people1, req, res, next) {
    next(null, { people1: people1, name: "Jeff" });
});

app.get('/', function(people2, res) {
    res.json({
        people2: people2
    });
});

require('http').createServer(app).listen(3008);
```

What I expect to see is:

``` json
{
    "people2": {
        "people1": { "name": "Bob" },
        "name": "Jeff"
    }
}
```

But what I get is `undefined is not a function` from `next(...)` call:

```
TypeError: undefined is not a function
    at app.get.res.json.people2 (/Users/floatdrop/express-di-test/index.js:11:5)
    at /Users/floatdrop/node_modules/express-di/lib/di.js:65:13
    at /Users/floatdrop/node_modules/express-di/node_modules/async/lib/async.js:227:13
    at iterate (/Users/floatdrop/node_modules/express-di/node_modules/async/lib/async.js:134:13)
    at async.eachSeries (/Users/floatdrop/node_modules/express-di/node_modules/async/lib/async.js:150:9)
    at _asyncMap (/Users/floatdrop/node_modules/express-di/node_modules/async/lib/async.js:226:9)
    at /Users/floatdrop/node_modules/express-di/node_modules/async/lib/async.js:216:23
    at /Users/floatdrop/node_modules/express-di/lib/di.js:37:9
    at callbacks (/Users/floatdrop/node_modules/express/lib/router/index.js:164:37)
    at param (/Users/floatdrop/node_modules/express/lib/router/index.js:138:11)
```

I suppose resolving in `factory` method is just not implemented yet, if so - do you have plans for it?

**Comment by luin** [comment]
This module only resolves the dependencies in the route-specific middlewares(`app[VERB](/*here*/)`) in order to avoid circular dependencies.

However, it's possible to support resolving in `factory` method(just throws exception when there are circular dependencies), but I think that will make things complicated.

You can have a common function to load `people1`:

```
var loadPeople1 = function(req, callback) {
  callback(null, { name: "Bob" });
};

app.factory('people1', function(req, res, next) {
  loadPeople1(req, next);
});

app.factory('people2', function(req, res, next) {
  loadPeople1(req, function(err, people1) {
    next(err, {
      people1: people1,
      name: 'Jeff'
    });
  });
});
```

**Comment by floatdrop** [comment]
Thanks for quick reply! I'm afraid suggested workaround is equivalent to throwing away dependency injection - which is not the perfect way. 

Anyway thanks again!

**Comment by floatdrop** [comment]
I will try to experiment in [express-dinja](https://github.com/floatdrop/express-dinja) for performance issues and circular dependencies.
