### ISSUE TITLE
doesn't work with express 4.x

### ISSUE THREAD

**Issue by alexgorbatchev** [luin/express-di#5]
http://runnable.com/U1aaR5tEqRQ9bJ_Q/dependency-injection-with-express-di-for-node-js-nodejitsu-and-npmawesome

seems like it doesn't do anything... first three arguments are req, res and next regardless

**Comment by luin** [comment]
This lib is only compatible with express 3.x currently. However, I'm working on a fix for this issue.

**Comment by luin** [comment]
I just publish express-di@4.0.0 which is compatible with Express 4.x.
